### Numpy 추가 예제

In [66]:
import numpy as np

In [39]:
# 1. array: 리스트를 배열로 변환
arr = np.array([1, 2, 3, 4, 5])
print('arr:\n', arr)

arr:
 [1 2 3 4 5]


In [40]:
# 2. arange: 연속된 수열 생성
rng = np.arange(0, 10, 2)
print('rng:\n', rng)

rng:
 [0 2 4 6 8]


In [41]:
# 3. linspace: 등간격 숫자 생성
lin = np.linspace(0, 1, 4)
print('lin:\n', lin)

lin:
 [0.         0.33333333 0.66666667 1.        ]


In [45]:
# 4. zeros: 0으로 초기화된 배열
z = np.zeros((2, 3))
print('zeros:\n', z)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [44]:
# 5. ones: 1로 초기화된 배열
o = np.ones((3, 2))
print('ones:\n', o)

ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [43]:
# 6. eye: 단위행렬 생성
I = np.eye(4)
print('eye:\n', I)

eye:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
# 7. random.seed: 난수 시드 고정
np.random.seed(42)

In [42]:
# 8. random.rand: 균등분포 난수
r1 = np.random.rand(2, 2)
print('rand:\n', r1)

rand:
 [[0.19967378 0.51423444]
 [0.59241457 0.04645041]]


In [38]:
# 9. random.randn: 정규분포 난수
r2 = np.random.randn(3, 3)
print('randn:\n', r2)

randn:
 [[-1.91328024 -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408]
 [-1.4123037   1.46564877 -0.2257763 ]]


In [37]:
# 10. reshape: 형태 변경
arr = np.array([[1, 2, 3, 4, 5], [7,9,11,13,15]])
reshaped = arr.reshape((5, 2))
print('reshaped:\n', reshaped)

reshaped:
 [[ 1  2]
 [ 3  4]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [46]:
# 11. flatten: 1차원으로 펼치기
flat = r2.flatten()
print('flat:\n', flat)

flat:
 [-1.91328024 -1.72491783 -0.56228753 -1.01283112  0.31424733 -0.90802408
 -1.4123037   1.46564877 -0.2257763 ]


In [54]:
# 12. concatenate: 배열 이어붙이기
a = np.array([1, 2]); b = np.array([3, 4])
cat = np.concatenate([a, b])
print('concatenate:\n', cat)

concatenate:
 [1 2 3 4]


In [56]:
# 13. vstack: 수직으로 쌓기
v = np.vstack([a, b])
print('vstack:\n', v)

vstack:
 [[1 2]
 [3 4]]


In [57]:
# 14. hstack: 수평으로 쌓기
h = np.hstack([a.reshape(2,1), b.reshape(2,1)])
print('hstack:\n', h)

hstack:
 [[1 3]
 [2 4]]


In [58]:
# 15. unique: 고유값 추출
uniq = np.unique([1,2,2,3,3,3])
print('unique:\n', uniq)

unique:
 [1 2 3]


In [59]:
# 16. argmax: 최대값 인덱스
idx_max = np.argmax([1,5,2,4])
print('argmax:\n', idx_max)

argmax:
 1


In [60]:
# 17. where: 조건 기반 인덱싱
w = np.where(arr % 2 == 0)
print('where (even indices):\n', w)

where (even indices):
 (array([1, 3]),)


In [61]:
# 18. clip: 값 범위 제한
cl = np.clip(rng, 1, 7)
print('clip:\n', cl)

clip:
 [1 2 4 6 7]


In [63]:
# 19. broadcast_to: 브로드캐스팅
bcd = np.broadcast_to([1,2,3], (3,3))
print('broadcast_to:\n', bcd)

broadcast_to:
 [[1 2 3]
 [1 2 3]
 [1 2 3]]


In [65]:
# 20. transpose: 축 순서 변경
t = np.transpose(r2, (1,0))
print('transpose:\n', t)

transpose:
 [[-1.91328024 -1.01283112 -1.4123037 ]
 [-1.72491783  0.31424733  1.46564877]
 [-0.56228753 -0.90802408 -0.2257763 ]]


### Pandas 추가 예제

In [67]:
import pandas as pd

# 샘플 데이터프레임 생성
data = {
    '이름': ['홍길동', '이영희', '김철수', '박민수'],
    '나이': [25, 30, None, 22],
    '성별': ['M', 'F', 'M', 'M'],
    '점수': [88, 92, 79, None]
}
df = pd.DataFrame(data)
print('DataFrame:', df)

DataFrame:     이름    나이 성별    점수
0  홍길동  25.0  M  88.0
1  이영희  30.0  F  92.0
2  김철수   NaN  M  79.0
3  박민수  22.0  M   NaN


In [69]:
# 1. Series: 1차원 배열 생성
s = pd.Series([1, 2, 3])
print('Series:\n', s)

Series:
 0    1
1    2
2    3
dtype: int64


In [ ]:
# 2. read_csv: CSV 읽기 (예시 주석 처리)
df_csv = pd.read_csv('파일.csv')
df_excel = pd.read_excel('파일.xlsx', sheet_name='1번시트')

In [70]:
# 3. head: 상위 5개
print('\nhead():\n', df.head())


head():
     이름    나이 성별    점수
0  홍길동  25.0  M  88.0
1  이영희  30.0  F  92.0
2  김철수   NaN  M  79.0
3  박민수  22.0  M   NaN


In [71]:
# 4. tail: 하위 5개
print('\ntail():\n', df.tail())


tail():
     이름    나이 성별    점수
0  홍길동  25.0  M  88.0
1  이영희  30.0  F  92.0
2  김철수   NaN  M  79.0
3  박민수  22.0  M   NaN


In [72]:
# 5. info: 데이터 정보
print('\ninfo():')
df.info()


info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      4 non-null      object 
 1   나이      3 non-null      float64
 2   성별      4 non-null      object 
 3   점수      3 non-null      float64
dtypes: float64(2), object(2)
memory usage: 260.0+ bytes


In [73]:
# 6. describe: 통계 요약
print('\ndescribe():\n', df.describe())


describe():
               나이         점수
count   3.000000   3.000000
mean   25.666667  86.333333
std     4.041452   6.658328
min    22.000000  79.000000
25%    23.500000  83.500000
50%    25.000000  88.000000
75%    27.500000  90.000000
max    30.000000  92.000000


In [74]:
# 7. columns: 컬럼명
print('\ncolumns:', df.columns)


columns: Index(['이름', '나이', '성별', '점수'], dtype='object')


In [75]:
# 8. index: 인덱스
print('\nindex:', df.index)


index: RangeIndex(start=0, stop=4, step=1)


In [76]:
# 9. shape: 크기
print('\nshape:', df.shape)


shape: (4, 4)


In [77]:
# 10. dtypes: 데이터 타입
print('\ndtypes:\n', df.dtypes)


dtypes:
 이름     object
나이    float64
성별     object
점수    float64
dtype: object


In [78]:
# 11. sort_values: 정렬
print('\nsort_values(score):\n', df.sort_values(by='점수'))


sort_values(score):
     이름    나이 성별    점수
2  김철수   NaN  M  79.0
0  홍길동  25.0  M  88.0
1  이영희  30.0  F  92.0
3  박민수  22.0  M   NaN


In [79]:
# 12. filter: 컬럼 선택
print('\nfilter(columns):\n', df.filter(items=['이름','점수']))


filter(columns):
     이름    점수
0  홍길동  88.0
1  이영희  92.0
2  김철수  79.0
3  박민수   NaN


In [80]:
# 13. groupby: 그룹화
grp = df.groupby('성별')
print('\ngroupby:', grp)


groupby: <pandas.core.groupby.generic.DataFrameGroupBy object at 0x11f644a40>


In [81]:
# 14. agg: 집계
print('\nagg mean:\n', grp.agg({'나이':'mean','점수':'mean'}))


agg mean:
       나이    점수
성별            
F   30.0  92.0
M   23.5  83.5


In [82]:
# 15. merge: 병합
df2 = pd.DataFrame({'이름':['홍길동','이영희'],'도시':['서울','부산']})
print('\nmerge:\n', pd.merge(df, df2, on='이름', how='left'))


merge:
     이름    나이 성별    점수   도시
0  홍길동  25.0  M  88.0   서울
1  이영희  30.0  F  92.0   부산
2  김철수   NaN  M  79.0  NaN
3  박민수  22.0  M   NaN  NaN


In [83]:
# 16. concat: 이어 붙이기
print('\nconcat axis=1:\n', pd.concat([df, df.filter(items=['이름','점수'])], axis=1))


concat axis=1:
     이름    나이 성별    점수   이름    점수
0  홍길동  25.0  M  88.0  홍길동  88.0
1  이영희  30.0  F  92.0  이영희  92.0
2  김철수   NaN  M  79.0  김철수  79.0
3  박민수  22.0  M   NaN  박민수   NaN


In [84]:
# 17. apply: 함수 적용
df['점수2'] = df['점수'].apply(lambda x: x**2 if pd.notnull(x) else x)
print('\napply square:\n', df)


apply square:
     이름    나이 성별    점수     점수2
0  홍길동  25.0  M  88.0  7744.0
1  이영희  30.0  F  92.0  8464.0
2  김철수   NaN  M  79.0  6241.0
3  박민수  22.0  M   NaN     NaN


In [85]:
# 18. isnull: 결측 확인
print('\nisnull:\n', df.isnull())


isnull:
       이름     나이     성별     점수    점수2
0  False  False  False  False  False
1  False  False  False  False  False
2  False   True  False  False  False
3  False  False  False   True   True


In [86]:
# 19. dropna: 결측 행 제거
print('\ndropna:\n', df.dropna(subset=['나이','점수']))


dropna:
     이름    나이 성별    점수     점수2
0  홍길동  25.0  M  88.0  7744.0
1  이영희  30.0  F  92.0  8464.0


In [87]:
# 20. fillna: 결측 채우기
print('\nfillna:\n', df.fillna({'나이':df['나이'].mean(),'점수':df['점수'].mean()}))


fillna:
     이름         나이 성별         점수     점수2
0  홍길동  25.000000  M  88.000000  7744.0
1  이영희  30.000000  F  92.000000  8464.0
2  김철수  25.666667  M  79.000000  6241.0
3  박민수  22.000000  M  86.333333     NaN


In [88]:
# 21. astype: 타입 변경
print('\nastype:\n', df['나이'].astype('float'))


astype:
 0    25.0
1    30.0
2     NaN
3    22.0
Name: 나이, dtype: float64


In [89]:
# 22. rename: 컬럼명 변경
print('\nrename columns:\n', df.rename(columns={'점수':'score'}))


rename columns:
     이름    나이 성별  score     점수2
0  홍길동  25.0  M   88.0  7744.0
1  이영희  30.0  F   92.0  8464.0
2  김철수   NaN  M   79.0  6241.0
3  박민수  22.0  M    NaN     NaN


In [90]:
# 23. drop: 행/열 제거
print('\ndrop column:\n', df.drop('점수2', axis=1))


drop column:
     이름    나이 성별    점수
0  홍길동  25.0  M  88.0
1  이영희  30.0  F  92.0
2  김철수   NaN  M  79.0
3  박민수  22.0  M   NaN


In [91]:
# 24. sample: 랜덤 샘플
print('\nsample 2 rows:\n', df.sample(2))


sample 2 rows:
     이름    나이 성별    점수     점수2
1  이영희  30.0  F  92.0  8464.0
0  홍길동  25.0  M  88.0  7744.0


In [92]:
# 25. pivot_table: 피벗 테이블
print('\npivot_table:\n', df.pivot_table(index='성별', values='점수', aggfunc='mean'))


pivot_table:
       점수
성별      
F   92.0
M   83.5


In [93]:
# 26. get_dummies: 원-핫 인코딩
print('\nget_dummies:\n', pd.get_dummies(df['성별']))


get_dummies:
        F      M
0  False   True
1   True  False
2  False   True
3  False   True


In [ ]:
# 27. to_csv: CSV 저장
df.to_csv('df_example.csv', index=False)
print("\nSaved DataFrame to 'df_example.csv'")

In [ ]:
# 29. drop_duplicates: 중복 제거
print('\ndrop_duplicates:\n', df.drop_duplicates())

In [ ]:
# 30. sort_index: 인덱스 기준 정렬
print('\nsort_index:\n', df.sort_index())